### ISSUE TITLE
Ammo system

### ISSUE THREAD

**Issue by wemlock** [wemlock/ZombieShooter#7]
Add ammo system

**Comment by Igris1617** [comment]
ammo types 7.62mm and 9mm need aadding help with 50 cal and 6.62

**Comment by wemlock** [comment]
ZPlayerController
Added Ammo + Max ammo Int Variables

Added Reload system which will reload when gun is empty  or when you press the R key 
Added Reloading Bool
Added ReloadCooldownTime Int
